In [2]:
import seaborn as sns

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [26]:
# 10 = 1000000 | 100000
# 100 = 10000000 | 1000000
# 1000 = 100000000 | 10000000
# 10000 = 1000000000 | 100000000

In [33]:
gap_s_1 = np.arange(10,21,1)
gap_s_2 = np.arange(20,31,1)
gap_s_3 = np.arange(30,41,1)
gap_s_4 = np.arange(40,51,1)
gap_s_5 = np.arange(50,61,1)
gap_s_6 = np.arange(60,71,1)
gap_s_7 = np.arange(70,81,1)
gap_s_8 = np.arange(80,91,1)
gap_s_9 = np.arange(90,101,1)
gap_s_10 = np.arange(100,111,1)
(gap_s_9,gap_s_10)

(array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]),
 array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110]))

In [34]:
gap_k_1 = np.arange(100,210,10)
gap_k_2 = np.arange(200,310,10)
gap_k_3 = np.arange(300,410,10)
gap_k_4 = np.arange(400,510,10)
gap_k_5 = np.arange(500,610,10)
gap_k_6 = np.arange(600,710,10)
gap_k_7 = np.arange(700,810,10)
gap_k_8 = np.arange(800,910,10)
gap_k_9 = np.arange(900,1010,10)
gap_k_10 = np.arange(1000,1110,10)
(gap_k_9,gap_k_10)

(array([ 900,  910,  920,  930,  940,  950,  960,  970,  980,  990, 1000]),
 array([1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100]))

In [47]:
def rate(arr_s,arr_k):
    arr_r = []
    for s in range(len(arr_k)):
        for k in range(len(arr_s)):
            val_d = arr_k[s]-arr_s[k]
            val_r = val_d/arr_s[k]
            arr_r.append([arr_s[k],arr_k[s],val_r])
    return sorted(arr_r)

In [48]:
print(rate(gap_s_1,gap_k_1))

[[10, 100, 9.0], [10, 110, 10.0], [10, 120, 11.0], [10, 130, 12.0], [10, 140, 13.0], [10, 150, 14.0], [10, 160, 15.0], [10, 170, 16.0], [10, 180, 17.0], [10, 190, 18.0], [10, 200, 19.0], [11, 100, 8.090909090909092], [11, 110, 9.0], [11, 120, 9.909090909090908], [11, 130, 10.818181818181818], [11, 140, 11.727272727272727], [11, 150, 12.636363636363637], [11, 160, 13.545454545454545], [11, 170, 14.454545454545455], [11, 180, 15.363636363636363], [11, 190, 16.272727272727273], [11, 200, 17.181818181818183], [12, 100, 7.333333333333333], [12, 110, 8.166666666666666], [12, 120, 9.0], [12, 130, 9.833333333333334], [12, 140, 10.666666666666666], [12, 150, 11.5], [12, 160, 12.333333333333334], [12, 170, 13.166666666666666], [12, 180, 14.0], [12, 190, 14.833333333333334], [12, 200, 15.666666666666666], [13, 100, 6.6923076923076925], [13, 110, 7.461538461538462], [13, 120, 8.23076923076923], [13, 130, 9.0], [13, 140, 9.76923076923077], [13, 150, 10.538461538461538], [13, 160, 11.307692307692308